export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_TODO_ITEMS = 'SET_TODO_ITEMS';
export const SET_FILTER_INPUT = 'SET_FILTER_INPUT';
export const SET_FILTER_DONE = 'SET_FILTER_DONE';
