export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
